//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marketplace.ADOModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarketplaceEntities : DbContext
    {
        public MarketplaceEntities()
            : base("name=MarketplaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<Basket> Basket { get; set; }
        public virtual DbSet<BasketProduct> BasketProduct { get; set; }
        public virtual DbSet<Like> Like { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductAddRequest> ProductAddRequest { get; set; }
        public virtual DbSet<ProductBirthRate> ProductBirthRate { get; set; }
        public virtual DbSet<ProductCategory> ProductCategory { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
